// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: april_value.proto

#ifndef PROTOBUF_april_5fvalue_2eproto__INCLUDED
#define PROTOBUF_april_5fvalue_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace april {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_april_5fvalue_2eproto();
void protobuf_AssignDesc_april_5fvalue_2eproto();
void protobuf_ShutdownFile_april_5fvalue_2eproto();

class value;

// ===================================================================

class value : public ::google::protobuf::Message {
 public:
  value();
  virtual ~value();
  
  value(const value& from);
  
  inline value& operator=(const value& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const value& default_instance();
  
  void Swap(value* other);
  
  // implements Message ----------------------------------------------
  
  value* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const value& from);
  void MergeFrom(const value& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 value = 1;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 1;
  inline ::google::protobuf::int32 value() const;
  inline void set_value(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:april.value)
 private:
  inline void set_has_value();
  inline void clear_has_value();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 value_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_april_5fvalue_2eproto();
  friend void protobuf_AssignDesc_april_5fvalue_2eproto();
  friend void protobuf_ShutdownFile_april_5fvalue_2eproto();
  
  void InitAsDefaultInstance();
  static value* default_instance_;
};
// ===================================================================


// ===================================================================

// value

// required int32 value = 1;
inline bool value::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void value::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void value::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void value::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline ::google::protobuf::int32 value::value() const {
  return value_;
}
inline void value::set_value(::google::protobuf::int32 value) {
  set_has_value();
  value_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace april

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_april_5fvalue_2eproto__INCLUDED
